#index:
#    path: /
#    controller: App\Controller\DefaultController::index

all_categories:
  path: /api/categories
  methods: [GET]
  controller: App\Controller\CategoryController::getAllCategories

create_category:
  methods: [POST]
  path: /api/categories
  controller: App\Controller\CategoryController::create

create_event:
  methods: [POST]
  path: /api/events
  controller: App\Controller\EventsController::create
